# my global config
global:
  scrape_interval:     15s # Intervalo de raspagem de métricas. O padrão é a cada 60s
  evaluation_interval: 15s # Intervalo para avaliação de regras. O padrão é a cada 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'account'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']
    
    