spring:
  application:
    name: account
  config:
    import: optional:configserver:http://localhost:9000
  data:
    mongodb:
      uri: 'mongodb://root:example@localhost:27017'
      database: account
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    log-spans: true
